### ISSUE TITLE
Instructions in Usage result in a error

### ISSUE THREAD

**Issue by Rick-van-Dam** [philnash/jekyll-gzip#3]
When working through [Usage](https://github.com/philnash/jekyll-gzip#usage) I noticed that the following command does not work:
```posh
PS C:\Users\RickvanDam\source\repos\Barsonax\Barsonax.github.io> JEKYLL_ENV=production bundle exec jekyll build
JEKYLL_ENV=production : The term 'JEKYLL_ENV=production' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ JEKYLL_ENV=production bundle exec jekyll build
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (JEKYLL_ENV=production:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Iam running this on windows.

**Comment by philnash** [comment]
Ah, apologies, I wrote the instructions and ran them on my Mac only. I guess this is not how Windows machines set environment variables.

I don't think you can set an environment variable inline like this on Windows. You could look into setting the `JEKYLL_ENV` variable [using the `set` command](https://ss64.com/nt/set.html) and then run `bundle exec jekyll build` after.

If you are able to get through this, I'd really appreciate a pull request that updates the Usage section with your experiences so that this gem can better support Windows developers too.

**Comment by Rick-van-Dam** [comment]
Already tried that but it seems jekyll is not fooled by that :)

**Comment by philnash** [comment]
Do any of the windows instructions in [this blog post help](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html)?

**Comment by Rick-van-Dam** [comment]
Tried it:
![image](https://user-images.githubusercontent.com/19387223/48416200-d2363280-e74f-11e8-8d61-9bbf83d4aa0d.png)

But when I run `bundle exec jekyll build` I don't see any gzip files.

**Comment by philnash** [comment]
Where are you looking for the gzipped files?

**Comment by Rick-van-Dam** [comment]
In the _site folder. I only see html, css etc files there.

**Comment by philnash** [comment]
Have you added `jekyll-gzip` to the `plugins` array in your `_config.yml`?

(I didn’t think this was necessary, but maybe it is and I’ll need to update the instructions.)

**Comment by Rick-van-Dam** [comment]
No I haven't done that yet. I only added it to the gemfile like the instructions said.

**Comment by philnash** [comment]
Ah, give that a go and let me know if it helps. Then I’ll update the Readme.

**Comment by philnash** [comment]
Was this the solution? Would love to get it into the README if that's what I was missing.

**Comment by Rick-van-Dam** [comment]
Haven't had the time yet to check.

**Comment by philnash** [comment]
Ok, let me know when you do! Thanks!

**Comment by Rick-van-Dam** [comment]
I still don't see any gzip's

EDIT: argh forgot to hit the save in vs code. Now I do see the gzip files
![image](https://user-images.githubusercontent.com/19387223/48555653-207b3b00-e8e2-11e8-9bec-ec8f8d19b61b.png)

Is it normal the normal assets are still there?

**Comment by Rick-van-Dam** [comment]
To summarize:
1. Add `jekyll-gzip` to your `plugins` node in `_config.yml`
2. Add `gem 'jekyll-gzip'` to your `Gemfile`
3. Run `bundle install`
4. Create a new `JEKYLL_ENV` environment variable and set the value to `production`
5. Close VS code and reopen it (so that it picks up the new variable) 
6. Run `bundle exec jekyll build`
7. You will see gzip files in the `_site` folder

**Comment by philnash** [comment]
Hooray! 

It is normal that the regular assets remain, if a user agent requests the asset but doesn't say that it will accept gzip as an encoding we want to be able to serve the original asset.

I will try to write up the extra instructions around environment variables for Windows. I have already added the bit about [adding to the `plugins` section in `_config.yml`](https://github.com/philnash/jekyll-gzip#installation).

Thanks for working through this with me!
