### ISSUE TITLE
Remove .gz from file name

### ISSUE THREAD

**Issue by insaurabh** [philnash/jekyll-gzip#4]
Can we **remove .gz from filename**, so that it can be used when content hosted on AWS s3.

Thank you.

**Comment by philnash** [comment]
Removing the `.gz` would overwrite the original file which I intend to maintain for use with your own web server that can react to requests with or without gzip. 

I believe that making this gem work well for those hosting on S3 would be good though. 

This could be built as an option, configurable in `_config.yml`, to overwrite the file and replace with the gzipped content. Would you be interested in working on that sort of thing?

**Comment by insaurabh** [comment]
> Removing the `.gz` would overwrite the original file which I intend to maintain for use with your own web server that can react to requests with or without gzip.
> 
> I believe that making this gem work well for those hosting on S3 would be good though.
> 
> This could be built as an option, configurable in `_config.yml`, to overwrite the file and replace with the gzipped content. Would you be interested in working on that sort of thing?

@philnash It will be great if I contribute in any form, but unfortunately currently I don't have sound knowledge of RUBY to extend this gem.I am just playing with  **jekyll** to make a website.

**Comment by philnash** [comment]
Fair enough. I will look into having a go at this when I get the time. 🙂

**Comment by philnash** [comment]
Apologies this took me a while to get to. With the release of version 2.1.0 you can now add the setting 

```yml
gzip:
  replace_files: true
```

Which will replace the files rather than creating new ones with the `.gz` extension.
